import type { DashboardData } from "./types";

export const MOCK_DASHBOARD: DashboardData = {
  welcome: {
    subtitle: "You have 12 products ready to publish today.",
  },
  metrics: [
    {
      id: "products",
      label: "Products",
      value: "142",
      delta: "+12 this week",
      deltaTone: "positive",
    },
    {
      id: "ai_content",
      label: "AI Content",
      value: "96",
      delta: "78% complete",
      deltaTone: "neutral",
    },
    {
      id: "creatives",
      label: "Creatives",
      value: "84",
      delta: "+18 this week",
      deltaTone: "positive",
    },
    {
      id: "published",
      label: "Published",
      value: "61",
      delta: "+9 this week",
      deltaTone: "positive",
    },
    {
      id: "success_rate",
      label: "Success Rate",
      value: "96.2%",
      delta: "+2.4 pts",
      deltaTone: "positive",
    },
    {
      id: "ready_today",
      label: "Ready Today",
      value: "12",
      delta: "5 items need attention",
      deltaTone: "attention",
    },
  ],
  focus: [
    {
      id: "publish",
      label: "12 products ready to publish",
      count: 12,
      priority: "low",
      actionLabel: "Review queue",
      href: "/publishing",
    },
    {
      id: "creatives",
      label: "8 products need creatives",
      count: 8,
      priority: "medium",
      actionLabel: "Generate",
      href: "/creatives",
    },
    {
      id: "content",
      label: "5 products need AI content",
      count: 5,
      priority: "medium",
      actionLabel: "Generate",
      href: "/content",
    },
    {
      id: "validation",
      label: "2 products failed validation",
      count: 2,
      priority: "high",
      actionLabel: "Review",
      href: "/content",
    },
  ],
  activity: [
    {
      id: "a1",
      icon: "check",
      title: "Pantry Organizer Bins AI content approved",
      description: "Reviewed and approved for Pinterest · ready to send to Creative Studio.",
      time: "5m ago",
    },
    {
      id: "a2",
      icon: "ai",
      title: "Over-Door Shoe Rack content generated",
      description: "Pinterest title, description, and hashtags drafted for review.",
      time: "22m ago",
    },
    {
      id: "a3",
      icon: "image",
      title: "Closet Shelf Organizer creative rendered",
      description: "home_01 pin template generated for the Home Essentials board.",
      time: "1h ago",
    },
    {
      id: "a4",
      icon: "publish",
      title: "Foldable Laundry Bag published",
      description: "Pin scheduled and published to the Laundry board.",
      time: "2h ago",
    },
    {
      id: "a5",
      icon: "import",
      title: "12 products imported",
      description: "Added from the Kitchen Storage bestsellers source.",
      time: "4h ago",
    },
    {
      id: "a6",
      icon: "category",
      title: "Under-Sink Organizer validation passed",
      description: "Content and pricing checks passed for the Bathroom category.",
      time: "1d ago",
    },
  ],
  pipeline: [
    { key: "imported", label: "Imported", count: 142 },
    { key: "research", label: "Research", count: 118 },
    { key: "ai", label: "AI", count: 96 },
    { key: "creative", label: "Creative", count: 84 },
    { key: "publishing", label: "Publishing", count: 12 },
    { key: "live", label: "Live", count: 61 },
  ],
  categories: [
    { id: "kitchen", name: "Kitchen Storage", products: 58, ready: 24 },
    { id: "laundry", name: "Laundry", products: 34, ready: 9 },
    { id: "bathroom", name: "Bathroom", products: 28, ready: 7 },
    { id: "closet", name: "Closet", products: 22, ready: 5 },
  ],
  quickActions: [
    {
      id: "add_product",
      title: "Add Product",
      description: "Expand your catalog from Amazon",
      href: "/products",
    },
    {
      id: "generate_content",
      title: "Generate AI Content",
      description: "products waiting for Pinterest copy",
      count: 5,
      href: "/content",
    },
    {
      id: "generate_creatives",
      title: "Generate Creatives",
      description: "approved products need imagery",
      count: 8,
      href: "/creatives",
    },
    {
      id: "open_publishing",
      title: "Open Publish Queue",
      description: "pins ready to go live today",
      count: 12,
      href: "/publishing",
    },
  ],
  services: [
    { id: "ai", label: "AI Service", statusLabel: "Online" },
    { id: "creative_engine", label: "Creative Engine", statusLabel: "Healthy" },
    { id: "pinterest", label: "Pinterest", statusLabel: "Connected" },
    { id: "workers", label: "Workers", statusLabel: "Idle" },
  ],
};
