import type { Product } from "./types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prd_expandable-basket",
    name: "Expandable Kitchen Storage Basket",
    category: "Kitchen Storage",
    price: 24.99,
    currency: "USD",
    rating: 4.7,
    reviewCount: 2134,
    asin: "B08FSVQ24P",
    source: "Amazon",
    imageUrl:
      "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?auto=format&fit=crop&w=900&q=70",
    description:
      "Two-tier expandable bamboo basket for countertop organization. Slides apart to fit cabinets and shelves.",
    progress: 35,
    health: "needs-attention",
    addedAt: "2026-07-24",
  },
  {
    id: "prd_laundry-bag",
    name: "Foldable Laundry Bag",
    category: "Home Storage",
    price: 19.99,
    currency: "USD",
    rating: 4.5,
    reviewCount: 5821,
    asin: "B075YV41GQ",
    source: "Amazon",
    imageUrl:
      "https://images.unsplash.com/photo-1582735689369-4fe89db7114c?auto=format&fit=crop&w=900&q=70",
    description:
      "Collapsible mesh laundry hamper with carry handles. Folds flat for compact storage between uses.",
    progress: 100,
    health: "ready",
    addedAt: "2026-07-18",
  },
  {
    id: "prd_pantry-bins",
    name: "Pantry Organizer Bins Set of 4",
    category: "Kitchen Storage",
    price: 34.99,
    currency: "USD",
    rating: 4.8,
    reviewCount: 3247,
    asin: "B0B968L1W4",
    source: "Amazon",
    imageUrl:
      "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=70",
    description:
      "Clear plastic storage bins with bamboo handles. Stackable for pantry and cabinet organization.",
    progress: 85,
    health: "ready",
    addedAt: "2026-07-15",
  },
  {
    id: "prd_closet-shelf",
    name: "Closet Shelf Organizer",
    category: "Home Storage",
    price: 29.99,
    currency: "USD",
    rating: 4.3,
    reviewCount: 1189,
    asin: "B08R7FP1HT",
    source: "Amazon",
    imageUrl:
      "https://images.unsplash.com/photo-1524260855046-f743b3cdad07?auto=format&fit=crop&w=900&q=70",
    description:
      "Six-slot hanging fabric organizer for folded clothes, towels, and accessories.",
    progress: 60,
    health: "ready",
    addedAt: "2026-07-12",
  },
  {
    id: "prd_shoe-rack",
    name: "Over-Door Shoe Rack",
    category: "Home Storage",
    price: 22.49,
    currency: "USD",
    rating: 4.4,
    reviewCount: 8974,
    asin: "B0BGS9RQFC",
    source: "Amazon",
    imageUrl:
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=900&q=70",
    description:
      "24-pocket over-the-door shoe organizer with clear pockets. Holds up to 12 pairs without floor space.",
    progress: 15,
    health: "blocked",
    addedAt: "2026-07-09",
  },
  {
    id: "prd_bathroom-shelf",
    name: "Bamboo Bathroom Shelf",
    category: "Home Storage",
    price: 27.99,
    currency: "USD",
    rating: 4.6,
    reviewCount: 2431,
    asin: "B0CPF3W9B2",
    source: "Amazon",
    imageUrl:
      "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=70",
    description:
      "Natural bamboo two-tier shelf with towel bar. Water-resistant finish for bathrooms and laundry rooms.",
    progress: 45,
    health: "needs-attention",
    addedAt: "2026-07-06",
  },
  {
    id: "prd_under-sink",
    name: "Under-Sink Organizer",
    category: "Kitchen Storage",
    price: 31.99,
    currency: "USD",
    rating: 4.2,
    reviewCount: 1654,
    asin: "B083SCJ8G8",
    source: "Amazon",
    imageUrl:
      "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=900&q=70",
    description:
      "Adjustable rolling organizer that fits around pipes. Two sliding drawers for cleaning supplies.",
    progress: 100,
    health: "ready",
    addedAt: "2026-07-03",
  },
  {
    id: "prd_hanging-closet",
    name: "Hanging Closet Organizer",
    category: "Home Storage",
    price: 17.99,
    currency: "USD",
    rating: 4.1,
    reviewCount: 3420,
    asin: "B0DNSYZRY8",
    source: "Amazon",
    imageUrl:
      "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=900&q=70",
    description:
      "Eight-pocket hanging organizer for scarves, belts, and accessories. Doubles closet storage instantly.",
    progress: 5,
    health: "blocked",
    addedAt: "2026-06-30",
  },
  {
    id: "prd_pantry-jars",
    name: "Stackable Pantry Storage Jars",
    category: "Kitchen Storage",
    price: 26.99,
    currency: "USD",
    rating: 4.7,
    reviewCount: 5122,
    asin: "B0DRXCR5NN",
    source: "Amazon",
    imageUrl:
      "https://images.unsplash.com/photo-1494859802809-d069c3b71a8a?auto=format&fit=crop&w=900&q=70",
    description:
      "Airtight glass jars with wooden lids for flour, sugar, and pantry staples. Stackable and dishwasher safe.",
    progress: 75,
    health: "ready",
    addedAt: "2026-06-27",
  },
];
