"use client";

import type { ComponentType } from "react";
import {
  BarChart3,
  ImageIcon,
  Info,
  Search,
  Send,
  Sparkles,
  Star,
} from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Separator } from "@/components/ui/separator";
import { ProgressBar } from "./progress-bar";
import { getCurrentStage, type Product } from "./types";
import { formatCompactNumber, formatCurrency, formatDate } from "./format";

const TAB_ITEMS = [
  { value: "overview", label: "Overview", icon: Info },
  { value: "research", label: "Research", icon: Search },
  { value: "ai-content", label: "AI Content", icon: Sparkles },
  { value: "creatives", label: "Creatives", icon: ImageIcon },
  { value: "publishing", label: "Publishing", icon: Send },
  { value: "analytics", label: "Analytics", icon: BarChart3 },
] as const;

function EmptySection({
  icon: Icon,
  title,
  hint,
}: {
  icon: ComponentType<{ className?: string }>;
  title: string;
  hint: string;
}) {
  return (
    <div className="flex flex-col items-center justify-center rounded-lg border border-dashed px-6 py-10 text-center">
      <Icon className="size-5 text-muted-foreground" />
      <p className="mt-2 text-sm font-medium text-foreground">{title}</p>
      <p className="mt-1 max-w-xs text-xs leading-relaxed text-muted-foreground">
        {hint}
      </p>
    </div>
  );
}

function OverviewTab({ product }: { product: Product }) {
  const stage = getCurrentStage(product.progress);

  const facts: { label: string; value: string }[] = [
    { label: "Price", value: formatCurrency(product.price, product.currency) },
    {
      label: "Rating",
      value: `${product.rating.toFixed(1)} (${formatCompactNumber(
        product.reviewCount,
      )})`,
    },
    { label: "Source", value: product.source },
    { label: "ASIN", value: product.asin },
    { label: "Added", value: formatDate(product.addedAt) },
  ];

  return (
    <div className="flex flex-col gap-5">
      <div>
        <h4 className="text-sm font-medium text-foreground">Description</h4>
        <p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">
          {product.description}
        </p>
      </div>

      <Separator />

      <dl className="grid grid-cols-2 gap-x-4 gap-y-4">
        {facts.map((fact) => (
          <div key={fact.label} className="flex flex-col gap-0.5">
            <dt className="text-xs text-muted-foreground">{fact.label}</dt>
            <dd className="text-sm font-medium text-foreground">
              {fact.value}
            </dd>
          </div>
        ))}
      </dl>

      <Separator />

      <div className="flex flex-col gap-3">
        <div className="flex items-center justify-between">
          <span className="text-sm font-medium text-foreground">
            Workflow progress
          </span>
          <span className="flex items-center gap-1 text-xs text-muted-foreground">
            <Star className="size-3.5 fill-amber-500/90 text-amber-500/90 dark:fill-amber-400/90 dark:text-amber-400/90" />
            {stage.label}
          </span>
        </div>
        <ProgressBar value={product.progress} label={undefined} />
      </div>
    </div>
  );
}

type ProductTabsProps = {
  product: Product;
};

export function ProductTabs({ product }: ProductTabsProps) {
  return (
    <Tabs defaultValue="overview" className="gap-0">
      <TabsList variant="line" className="w-full justify-start overflow-x-auto">
        {TAB_ITEMS.map((tab) => (
          <TabsTrigger key={tab.value} value={tab.value} className="gap-1.5">
            <tab.icon className="size-3.5" />
            {tab.label}
          </TabsTrigger>
        ))}
      </TabsList>

      <div className="pt-5">
        <TabsContent value="overview">
          <OverviewTab product={product} />
        </TabsContent>
        <TabsContent value="research">
          <EmptySection
            icon={Search}
            title="No research notes yet"
            hint="Competitive analysis, demand signals, and seasonality insights will appear here once the research pipeline runs."
          />
        </TabsContent>
        <TabsContent value="ai-content">
          <EmptySection
            icon={Sparkles}
            title="No AI content generated"
            hint="Product descriptions, titles, and pin copy generated by the AI pipeline will appear here."
          />
        </TabsContent>
        <TabsContent value="creatives">
          <EmptySection
            icon={ImageIcon}
            title="No creatives yet"
            hint="Designed Pins and image variations for this product will appear here when creatives are generated."
          />
        </TabsContent>
        <TabsContent value="publishing">
          <EmptySection
            icon={Send}
            title="Not scheduled for publishing"
            hint="Publish slots and board assignments for this product will appear here once scheduled."
          />
        </TabsContent>
        <TabsContent value="analytics">
          <EmptySection
            icon={BarChart3}
            title="No analytics available"
            hint="Impressions, saves, and engagement metrics will appear here after this product is published."
          />
        </TabsContent>
      </div>
    </Tabs>
  );
}
